### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by alainlankers** [highball8/wordpress_with_docker#1]
Hello
I am following this tutorial step by step. Right now I am stuck on part 3 :https://www.massolit-media.com/tech-writing/wordpress-and-docker-customize-a-container/

The tutorial says:

_Now I have customized this container, I want to create my own image of it so that I can use it in the future. Here’s how you “commit” a Docker container, or convert it to an image, locally:_

```
# docker stop wp
# docker commit wp wp-custom:local_0-1
```

When I follow these step I get an error : docker command not found:

```
root@f224f56776a2:/usr/local/etc/php# docker stop wp
bash: docker: command not found
```

Any ideas how I can proceed?

**Comment by highball8** [comment]
Hi, @alainlankers. Sorry for the slow reply; I am not on here much.

It looks to me that you are running that `docker stop wp` from *within* the Docker container. I am guessing that because I see the `root@f224f56776a2:/usr/local/etc/php#` prompt.

My instructions could be clearer, so I will update the tutorial to specify which tasks should be performed on the command line of your workstation (laptop, whatever) and from within the container.

Thank you for the feedback!

**Comment by alainlankers** [comment]
Hi @highball8 ! Thanks for the feedback. 
Yes you are right, I am running that stop command from within the container.
Looking forward for the updated instructions. Keep me posted.
Thanks!

**Comment by highball8** [comment]
@alainlankers The page is updated.

I added this text: https://www.massolit-media.com/tech-writing/wordpress-and-docker-customize-a-container/

Note: To better communicate when I am interacting with the command line of the host machine and when I am using the command line within the Docker container, I will use the following notation:

$: The prompt on the host machine.
<Container-CLI>#: The prompt of the Docker container.

Although I think this item is the only part of the tutorial series that uses the container CLI.

Thanks again for pointing out the issue.

**Comment by highball8** [comment]
I'm closing this as I have explained the issue updated the associated WordPress content to make it clearer. See comments above.

**Comment by alainlankers** [comment]
Thanks so much for the update! It's all clear and working fine. You have been a great help for understanding this matter. Thanks for your time and help.
